### ISSUE TITLE
Additional indexes for pedsnet data model

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#100]
Updates and deletes on tables in the data model are prohibitively slow without indexes on the foreign key fields.  The following are the indexes in pedsnet v2 that need to be created:

```
create index on observation(provider_id);
create index on condition_occurrence(provider_id);
create index on measurement(provider_id);
create index on visit_occurrence(care_site_id);
create index on visit_occurrence(provider_id);
create index on drug_exposure(provider_id);
create index on person(care_site_id);
create index on person(location_id);
create index on person(provider_id);
```

The test case driving this suggestion: even in a small case (small site data sitting in warehouse, add another small site's provider, care_site, and location data, then purge that added data), the difference is huge.  Without indexes, the purge never finished (exceeded 9 hrs).  With indexes, the purge took 1 minute.  The indexes will also benefit joins.  FWIW, Django automatically creates indexes on foreign key fields, although few databases do so automatically.

**Comment by bruth** [comment]
Added in #101
