### ISSUE TITLE
Remove superfluous indexes from PEDSnet models

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#102]
Looking at v2, I see some indexes defined in indexes.csv that are redundant with primary key indexes automatically created by the primary key constraints.

TODO: remove these from v2 and v2.1.

model|version|name|unique|table|field|order
---|---|---|---|---|---|---
pedsnet|v2|idx_concept_concept_id|Yes|concept|concept_id|asc
pedsnet|v2|idx_person_id|Yes|person|person_id|asc
pedsnet|v2|idx_visit_payer_id|Yes|visit_payer|visit_payer_id|asc
pedsnet|v2|idx_vocabulary_vocabulary_id|Yes|vocabulary|vocabulary_id|asc

**Comment by aaron0browne** [comment]
Yes, see the result of this duplication in PEDSnet/Data_Models#197.
