### ISSUE TITLE
Incorrect required fields

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#109]
See https://github.com/chop-dbhi/data-models-service/issues/18

[Comments below added by KM]:

In particular, for `pedsnet` `2.1.0`:

*  In the `drug_exposure` table, the `drug_exposure_end_time` field is *not* marked as NOT NULL by the 2.1 ETL conventions, but it is required in the data model (and is not in `not_nulls.csv`).
* In the `measurement` table, the `measurement_time` field *is* marked as NOT NULL by the ETL conventions, but it is not required in the data model (and does not appear in `not_nulls.csv`).
* In the `measurement` table, the `unit_source_value` field is *not* marked as NOT NULL by the ETL conventions, but it is required in the data model (and is not in `not_nulls.csv`).

The above list covers the `drug_exposure` and `measurement` tables, which are ones for which discrepancies have been reported by sites (Colorado).

**Comment by murphyke** [comment]
Added a few specific fields noticed by Colorado.

**Comment by aaron0browne** [comment]
Fixed in #115.
