### ISSUE TITLE
Handling line endings

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#116]
If csv files go into the repo with carriage returns, it makes diffs annoying (e.g. in github PRs).

@bruth @aaron0browne @burrowse What do we feel about making the repo normalize to LF?  Here is a recipe from http://git-scm.com/docs/gitattributes:

```sh
$ echo "* text=auto" >>.gitattributes
$ rm .git/index     # Remove the index to force Git to
$ git reset         # re-scan the working directory
$ git status        # Show files that will be normalized
$ git add -u
$ git add .gitattributes
$ git commit -m "Introduce end-of-line normalization"
```

See also: https://help.github.com/articles/dealing-with-line-endings/

**Comment by bruth** [comment]
For our own sanity that would be good. I pushed an update for the service to handle carriage returns properly.

**Comment by murphyke** [comment]
Hah, way to pay attention, Kevin.  Obviously Aaron noticed the same thing.  Already done.
