### ISSUE TITLE
Issues in creating pcornet schema from automated ddl

### ISSUE THREAD

**Issue by burrowse** [chop-dbhi/data-models#132]
When trying to create the cornet schema from the automated ddl, I am getting numeric scale and precision errors for:

CREATE TABLE dispensing (
ERROR:  NUMERIC scale 16 must be between 0 and precision 8
LINE 2: dispense_amt NUMERIC(8, 16), 

CREATE TABLE harvest (
ERROR:  NUMERIC scale 16 must be between 0 and precision 8
LINE 4: cdm_version NUMERIC(8, 16), 

CREATE TABLE lab_result_cm (
ERROR:  NUMERIC scale 16 must be between 0 and precision 8
LINE 26: result_num NUMERIC(8, 16), 

CREATE TABLE prescribing (
ERROR:  NUMERIC scale 20 must be between 0 and precision 2
LINE 9: rx_days_supply NUMERIC(2, 20), 

CREATE TABLE pro_cm (
ERROR:  NUMERIC scale 16 must be between 0 and precision 8
LINE 11: pro_response NUMERIC(8, 16) NOT NULL, 
                      ^
CREATE TABLE vital (
ERROR:  NUMERIC scale 16 must be between 0 and precision 8
LINE 3: diastolic NUMERIC(8, 16), 
                  ^
Are the numbers flip-flopped? @aaron0browne

**Comment by aaron0browne** [comment]
Yup, it seems that way.

**Comment by aaron0browne** [comment]
I'll fix and submit a PR.

**Comment by bruth** [comment]
Fixed in #133
