### ISSUE TITLE
OHDSI added new column in drug_strength, denominator value

### ISSUE THREAD

**Issue by burrowse** [chop-dbhi/data-models#134]
While building the v2.2 vocab snapshot it was discovered that OHDSI created a new column in the drug_strength table...this will need to be updated in our DDL generation scripts. 

See reference code, this is not updated as yet on their wiki
https://github.com/OHDSI/Vocabulary-v5.0/blob/41b41adf38297c36c6fbe1cc53178f327c31099c/working/DevV5_DDL.sql

**Comment by aaron0browne** [comment]
Haha, I didn't see that you were tackling this before I did. I guess it's better than having no one working on it...

**Comment by aaron0browne** [comment]
Does my PR look good to you?

**Comment by burrowse** [comment]
Thanks! Looks good.
