### ISSUE TITLE
Add concept table to PEDSnet models

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#14]

**Comment by aaron0browne** [comment]
My understanding of the PEDSnet data model is that it specifically relies on the OMOP vocabulary tables (of which concept is one).

**Comment by bruth** [comment]
Right, my pending PR includes both of the concept and vocabulary tables. I saw it from the standpoint of following the reference fields in the other parts of the data model.

**Comment by aaron0browne** [comment]
I can see multiple ways of expressing the reliance of pedsnet on omop vocabulary tables, but I think in the long term it makes the most sense to include the concept tables in both CDMs, so I support this step in that direction.
