### ISSUE TITLE
Final tweak to pedsnet 2.4.0 era table additions

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#154]
@burrowse  For the `dose_era` table, the `dose_value` column is not mentioned in the schema/dose_era.csv file. This causes an error in the data-models-sqlalchemy service but not data-models-service.

Can you add that? I will open an issue for data-models-service to catch this in the future.  And this repo itself should run a test on a PR. I was getting around to fixing that but was too slow. 

/cc @eceowl

**Comment by burrowse** [comment]
@murphyke Thanks for catching this. Sorry for leaving that column out. I have added it and I'll submit a pull request now. Would I need to also download the data-models-sqlalchemy service to validate next time?

**Comment by murphyke** [comment]
@burrowse I think by next time we'll have the tests (which are based on dmsa) working again, but for now I will hand-verify with dmsa. If you're game, it can be fun to run dmsa yourself. There is no better sanity check than generating DDL before and after and doing a diff.

**Comment by murphyke** [comment]
@eceowl The 2.4.0 fix was merged almost 30 minutes ago. I think the data models service polls for updates every hour, so within 35 minutes, the 2.4.0 DDL should be available.
