### ISSUE TITLE
CI configuration

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#163]
@aaron0browne For fork PRs to be tested, I think the following changes should be made in the CircleCI advanced settings:

* "Build forked pull requests" => "On"
* "Pass secrets to builds from forked pull requests" => "Off"

Can you do that? I don't think I have the permissions. The only chop-dbhi repo that I can see from CircleCI is `grin_harvest`.

**Comment by aaron0browne** [comment]
Done, but I'm now remembering a reason #157 languished for so long, which is that I think some parts of the CI might need those secrets? Maybe its just the deployment step?

**Comment by murphyke** [comment]
https://circleci.com/docs/1.0/fork-pr-builds/. I think it's only deployment that would need the CircleCI UI-configured secrets, because the configuration worked for me when I hooked CircleCI up to a fork of data-models (and then PR'd a fork of that).

**Comment by aaron0browne** [comment]
Great!
