### ISSUE TITLE
Fix omop 5.0.0

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#166]
The data-models-sqlalchemy service currently throws exceptions when trying to generate DDL for OMOP v5.

Although this DDL may not be of interest to anyone, we should nevertheless fix this so the continuous integration test builds are useful. 

The errors are:

```
ERROR: no fields for table adt_occurrence
ERROR: no fields for table measurement_organism
ERROR: no fields for table visit_payer
```

These tables are listed in `tables.csv`, but there are no corresponding .csv files in `definitions/`. There must also be corresponding .csv files in `schema/`.

**Comment by burrowse** [comment]
Okay fixed @murphyke

**Comment by aaron0browne** [comment]
Just pushed an analogous commit to master, after noticing that the fix was only in Evanette's fork. Should be trickling down to the various services soon.
