### ISSUE TITLE
Possible Changes for Data Models Generator

### ISSUE THREAD

**Issue by burrowse** [chop-dbhi/data-models#167]
Is it possible to change the default type of datetime to datetime2 for SQL Server DDL Generation in the PEDSnet model? I ask as OHDSI has recently changed their default year to 1070 which according to St.Louis is not supported by the datetime field type but is supported by the datetime2 field? Thoughts?

Another issue is around the "VERSION_HISTORY"."DMS_VERSION", can we change the field size to be larger or take a look at what is currently being generated for insertion into this field? It is currently 16 and what is being generated is 21 characters. An example is  '1.0.3-beta.16+8c2d069’.

@murphyke @aaron0browne

**Comment by aaron0browne** [comment]
Done.
