### ISSUE TITLE
Add schema, constraint, and index files for PEDSnet models

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#17]
See #5 for the original discussion, but here are relevant fields:

Field schema file fields: `schema/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Name of the table.
- `field` (required) - Name of the field.
- `type` (required) - Data type of the field.
- `length` - Describes the maximum length of the value.
- `precision` - Describes the precision of value specified in `type`, typically for a number.
- `scale` - Describes the scale of the value specified in `type`, typically for a number.
- `default` - Defines the default value for the field.

Constraints file fields: `constraints/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Table the constraint applies to.
- `field` - One or more fields the constraint applies to.
- `type` (required) - Type of constraint.
- `name` - Suggested name of the constraint

Indexes file fields: `indexes/<table>.csv`

- `model` (required) - Name of the model.
- `version` (required) - Version of the model.
- `table` (required) - Name of the table.
- `field` (required) - One or more fields the index applies.
- `name` - Suggested name of the index.
- `type` - Suggested type of the index.
- `unique` - If true, denotes a unique index.
- `order` - For ordered indexes, specifies `asc` or `desc`

This issue applies to v1 and v2:

- [ ] Fill in remaining schema fields (default values)
- [ ] Constraints
- [ ] Indexes

**Comment by bruth** [comment]
@aaron0browne How would you like to break up this work?

**Comment by aaron0browne** [comment]
No problem however you want to break it up. I probably won't be able to start work on it until tomorrow/next week. It would be nice to do OMOP as well. How about you do PEDSnet v2 and OMOP v5, since that is a pretty clear translation of the [official DDL](https://github.com/OHDSI/CommonDataModel/tree/master/PostgreSQL), and I'll tackle PEDSnet v1 and OMOP v4, since the historical specifications are a little more squirrelly?

**Comment by bruth** [comment]
That sounds good, thank you.

**Comment by bruth** [comment]
PR #20 contains the PEDSnet v2 and OMOP v5 components.

**Comment by bruth** [comment]
For constraint types I used `not null` and `primary key`. For indexes I added `unique` and `order` fields, however I am not sure if this is necessary for general DDL.

**Comment by bruth** [comment]
Closing this since the majority of this data has been added. New issues can be opened for specific tasks.
