### ISSUE TITLE
Table: hash_token | data type: varchar(18)

### ISSUE THREAD

**Issue by ChavanShweta** [chop-dbhi/data-models#261]
OP-1090
@burrowse 
- [x] PCORnet patid harmonization updates requires hash_token table patid to be same length as other table patid. Hash_token patid updated from character varying 18 to [character varying 256]( https://github.com/chop-dbhi/data-models/blob/master/pcornet/v6.0/schema/hash_token.csv#L2)

Everything else looks good. Thanks.

**Comment by burrowse** [comment]
Thanks @ChavanShweta! This has been updated in PR #262 and has been updated in the DDL.
