### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#37]
See `pedsnet.v2.concept.concept_class_id.description` for the example:

```
"The category or class of the concept along both the hierarchical tree as well as different domains within a vocabulary. Examples are â€œClinical Drugâ€, â€œIngredientâ€, â€œClinical Findingâ€ etc. "
```

**Comment by aaron0browne** [comment]
Changed the encoding of my browser to unicode and the characters rendered perfectly.

**Comment by bruth** [comment]
Marking this as a bug since the files themselves should be using all valid UTF-8 characters, however this is a lower priority.
