### ISSUE TITLE
Remove dependence on model definition

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/data-models#46]
Currently, the directory of the datamodel.json file is walked and bound to the declared model. This presumes a structure which is not necessary since each file type can stand alone (each one contains the model and version).

The first step is to replace datamodel.json with a CSV file (see #45), then update the walk algorithm to rely on the model specified in the file.

**Comment by aaron0browne** [comment]
I believe this is done, right?

**Comment by bruth** [comment]
Yep.
