### ISSUE TITLE
Add pedsnet v2 flavor of i2b2 data models

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#47]
Will reorganize the i2b2 directory to contain V1 and V2; existing stuff will move into V1.  The V2 directory will be populated with content that can be digested by https://github.com/chop-dbhi/data-models, i.e. a handful of CSV files describing the data model.

**Comment by bruth** [comment]
Are you labeling it `v1` relative to how PEDSnet is using it? If so, it may be more appropriate to put in a separate repository. As you mentioned today, i2b2 doesn't really have *versions* and since they encourage extending the base schema, baseline or custom versions for a project should be labeled and/or versioned specific to the project.

**Comment by murphyke** [comment]
I was going to name the model `i2b2_for_pedsnet`, with versions 'v1' and `v2` (referring to PEDSnet version).

**Comment by bruth** [comment]
Ok, sounds good.

**Comment by bruth** [comment]
@murphyke Just a heads up that I implemented a [generator](https://github.com/chop-dbhi/data-models-generator) that can connect to a relational database and generate the CSV files. That may provide an easier starting point if you already have the Oracle database in place.

**Comment by murphyke** [comment]
Yeah, I saw that, that's fantastic.  Thanks.

**Comment by murphyke** [comment]
Actually, the i2b2_for_pedsnet model should go in the PEDSnet/Data_Models repo.

**Comment by murphyke** [comment]
Byron,  I have the "i2b2 for pedsnet" v2 csv data model files done.  I am reopening this ticket just to see what your current thinking is with regard to where these should live.  I think Aaron is leaning toward having them go here.  Since this data model is related to both i2b2 1.7 and to pedsnet v2, it might be more practical to keep all the data models together ....

**Comment by bruth** [comment]
The service can merge models from multiple repositories, so whatever is easiest for maintaining the files. I want to break out the service code from this repository into a separate one or we could move each of the models to separate repositories. Again whatever is easiest for maintaining these files going forward.

**Comment by murphyke** [comment]
This is done.
