### ISSUE TITLE
Add constraints and indexes to the JSON service endpoint

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#48]

**Comment by bruth** [comment]
Both are included in the [output](https://github.com/chop-dbhi/data-models/blob/master/app/service/model.go#L420-L427). Indexes should be for [PEDSnet v2](http://data-models.origins.link/schemata/pedsnet/v2?format=json), but there are no files in the repository declaring unique constraints.

**Comment by bruth** [comment]
It would be great if you could add them!

**Comment by aaron0browne** [comment]
I believe this was closed as of #57
