### ISSUE TITLE
Errors in csv data found through DDL work

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#59]
Specific issues:

- `pedsnet.v1.person.day_of_birth.type` from `numder` -> `number`
- `pedsnet.v2.vocabulary.vocabulary_concept_id` from `''` -> `integer`
- `pedsnet.v1.indexes.idx_visit_person_id` and `...idx_visit_concept_id` replaced by `...idx_visit_person_date`
- `omop.v5.cohort_definition` definitions field `cohort_instantiation_date` -> `cohort_initiation_date`
- `omop.v5.concept` definitions remove field `concept_level`
- `omop.v5.fact_relationship` schema field `domain_concept_id` split into `..._1` and `..._2`
- `omop.v5.constraints.primary_keys.xpk_cohort_attribute` remove in favor of `xpk_cohort_definition`

Larger issues:

- Can the JSON object always adhere to the defined structure, even if the underlying lists are empty? (For example, can the [pcornet.v3 json](http://data-models.origins.link/schemata/pcornet/v1?format=json) have `schema.constraints.not_null` and `foreign_keys` set to `[]` instead of `none`?)
- ~~The [omop.v4 json](http://data-models.origins.link/schemata/omop/v4?format=json) endpoint is not returning anything.~~
- Several `pcornet.v1.schema.vital` fields have `integer` types with a `length` attribute, which is choking the SQLAlchemy constructors... What is the intended meaning of this attribute? Should these be `number` types (with the `length` attribute moved to `precision` instead)?
- Downcase all object names in the `pcornet` models.
- Several `i2b2.v1_7.schema` fields share the `integer` with `length` problem described above.
- Is `timestamp` as used in `i2b2.v1_7` significantly different from `datetime` elsewhere?

**Comment by bruth** [comment]
I updated the service to ensure the arrays are initialized: bbf73bb9b04

**Comment by bruth** [comment]
Which means the `not_null` and `foreign_keys` array will be empty arrays rather than nil.
