### ISSUE TITLE
Add indexes for i2b2_pedsnet

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#73]
Currently there is just one; committed by accident (which will be removed by a pending PR).  The old original i2b2 indexes are very heavy-weight and largely a huge waste of disk and load time as far as pedsnet is concerned.

**Comment by bruth** [comment]
Is this still relevant? If so, can you put together a PR?

**Comment by murphyke** [comment]
I put it on my short-term TODO list to look at this

**Comment by aaron0browne** [comment]
Done. Closing.
