### ISSUE TITLE
Needs change in table definition

### ISSUE THREAD

**Issue by parthdivekar** [chop-dbhi/data-models#78]
In Oracle Section under FULL DDL, First table has following 
   conditionid VARCHAR2 NOT NULL, 
    encounterid VARCHAR2, 
    patid VARCHAR2 NOT NULL, 
    raw_condition VARCHAR2, 
    raw_condition_source VARCHAR2, 
    raw_condition_status VARCHAR2, 
    raw_condition_type VARCHAR2, 

Varchar2 without size specifications will result in errors.

Parth

**Comment by aaron0browne** [comment]
Thanks @parthdivekar!

The PCORnet V3 specification fails to specify a size for these fields (noting them only as "Text(x)". So I don't think we should change the model definition files, but instead alter the DDL generation to insert a large default size value. What do you think?

**Comment by aaron0browne** [comment]
I'm going to go ahead and move this to the chop-dbhi/data-models-sqlalchemy and implement the default size when generating Oracle DDL, as I suggested above.

**Comment by parthdivekar** [comment]
Aaron

That’s fine. Since these are the fields to store RAW source data you can set it to varchar2(4000).

Hope this helps.

Parth

**Comment by aaron0browne** [comment]
Just saw this, on my first pass I set to 255 CHAR, but if you think 4000 will be required, we can definitely do that. Please follow progress and post additional comments at chop-dbhi/data-models-sqlalchemy#4
