### ISSUE TITLE
Strings with undefined lengths in upstream data model definition?

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#79]
This has come up for PCORnet V3 on Oracle DBMS: chop-dbhi/data-models-sqlalchemy#4

How should we handle these fields? Clearly one default value (which could be added at the DDL generation layer) is not good enough as some of the fields need to accommodate large amounts of text (raw source fields, e.g.) while some of them should be indexed (foreign key fields, e.g.).

My first thought compromise is to define length for those that need to be indexed here, leave the raw source value fields without defined length, and set a large default in the DDL generation layer. Thoughts?

**Comment by bruth** [comment]
This sounds like a database-specific issue? If a length is not specified then what is the appropriate default length? If this is what you are describing then specifying a default length (even if it is not specified in the spec) may be the best option.

**Comment by aaron0browne** [comment]
Resolved in chop-dbhi/data-models-sqlalchemy#4 without needing a change to the definitions stored here.
