### ISSUE TITLE
Versioning of data model representation?

### ISSUE THREAD

**Issue by aaron0browne** [chop-dbhi/data-models#80]
As we start to use this resource downstream, it would be nice to know when the representation of a given data model in this repo changes. For example, the representation of PEDSnet v2 has already changed several times. I suppose the data-models-service could simply expose the current git commit sha1, but it might be nice to have a semver style incrementing number.

Thoughts?

**Comment by bruth** [comment]
How do you intend this version to be used? For display only or relative time?

**Comment by aaron0browne** [comment]
Not sure what you mean by relative time, but I think for display only. For example, when the dcc-loader uses DDL from the data-models-sqlalchemy service, it might be nice to emit an origins fact with the versions of the data-models, data-models-service, and data-models-sqlalchemy packages so that we can keep track of which databases are using up-to- or out-of-date schemas...

**Comment by bruth** [comment]
> For display only or relative time?

That is definitely cryptic. What I meant was, will it be used to inform people of the version relative to time vs. a SHA1 which is opaque (relative to time). For example, if someone seems `1.5` and then `1.7` vs. `b2ac341` and then `5afec13`, the former would be more informative of how many versions have passed (although I doubt people would really keep track).

**Comment by aaron0browne** [comment]
In recent packages, I've been using an extended `maj.min.micro-lvl+serial.sha1` for all but final level releases, which get shortened to `maj.min.micro`, since sometimes we'll change code (thereby generating an additional serial and/or sha1) without wanting to increment the micro version (within work on a branch, for example). It's big and ungainly, but complies with semver 2.0 and gives all the information.

**Comment by aaron0browne** [comment]
Any more thoughts here, @bruth? Implementation-wise, I think the model is the right level of granularity, so we could add a `release_version` column to the `models.csv` file, which would hold a `maj.min.micro` number and a `release_level` column, which would hold `alpha|beta|final`.

**Comment by aaron0browne** [comment]
And then the client would be responsible for defining the `serial` and getting the `sha1` from git.

**Comment by bruth** [comment]
What is the policy for incrementing the version? For v2, is the major number always `2`? What denotes a minor increase and what does the significance of the change mean to consumers? What are the boundaries for breaking changes? Type change? Length change?

**Comment by aaron0browne** [comment]
After talking with @mgkahn and @toanong, they are very impressed and excited about the possibilities of this work. They also confirmed my sense that stable strong versioning, as a dependency for consistent releases and version diffing (even within major data model versions), is an important next step.

I'm now thinking that it may be enough to package the version of this repo's representation of a data model into the data model version number, like so:

- `maj.min.micro` would be the responsibility of the data model creators, and would represent actual changes to the data model specification.
- `lvl` and `serial` would be specific to the representation of the data model in CSV format. So, a particular `maj.min.micro` specification of the data model could have release levels as well as a serially increasing "build number" that would increment for any change to the CSV data (that is *not* in response to a specification change).
- the `sha1` would represent an actual git commit to the repo holding the CSVs.

I like this because it ties the release of a data model to the release of the CSV format representation, which is a goal of the project, rather than distinguishing between the two by having two version numbers.

**Comment by bruth** [comment]
So `maj.min.micro` increments at the digression of the maintainers and is driven by functional changes or significant semantic changes. This makes sense. Based on your description, it sounds like `lvl` and `serial` are to be automatically incremented for *every* change make to the CSV files (even if insignificant like a grammatical error). Other than a more visually appealing version number, it sounds like there is no semantic difference between `lvl`/`serial` and `sha1`. Can we simplify this an just use `maj.min.micro` and `sha1`? As I understand it, the need for a *strong* version is so a data model can be explicitly referenced and not variable by time (which a git `sha1` provides).

**Comment by bruth** [comment]
Digression => discretion

**Comment by aaron0browne** [comment]
`lvl` provides a description of the maturity of the data model representation (`alpha|beta|final`). `serial` provides an incrementing number so that different versions of data model representations can be quickly compared for precedence. `sha1` provides a link to the representation itself through git history. I see all of these as being important...

The added value of `lvl` and `serial` rest entirely on the increase in human usability of the data model version. At a glance, an ETL writer can know whether they are interacting with a pre-release or mature representation of the data model and which of two versions is more recent.

**Comment by bruth** [comment]
Thanks, that is more clear to me and I support it.

**Comment by bruth** [comment]
@aaron0browne You can add the `release_version` and `release_level` to the `models.csv` files for each data model and I will work on https://github.com/chop-dbhi/data-models-service/issues/1

**Comment by bruth** [comment]
I will also integrate these two new columns in https://github.com/chop-dbhi/data-models-service/issues/4

**Comment by aaron0browne** [comment]
So, since the `maj.min.micro` is at the discretion of the model maintainers, it seems that those could all be stored together in the existing `version` column of `models.csv`, so I'm thinking I'll add the planned `release_level` column to hold `alpha|beta|final` and a `release_serial` column to hold the sequentially incrementing `serial` number, instead of a `release_version` column we discussed before fleshing out the version semantics.

PR on the way.

**Comment by bruth** [comment]
One other thing to note is that the current `version` field is no semver compliant. It should not have the `v` prefix and most of them do not contain the minor and micro levels. Can you update these as well?

**Comment by bruth** [comment]
Next up for me is adding the git sha to the release info for the particular model: https://github.com/chop-dbhi/data-models-service/issues/6

**Comment by aaron0browne** [comment]
I'll update the version fields shortly.
