### ISSUE TITLE
PEDSnet CDM: All source values should be made varchar 

### ISSUE THREAD

**Issue by writetoritu** [chop-dbhi/data-models#93]
e.g. In PEDSnet.drug_exposure: effective_drug_dose_source_value is currently listed as "float"

**Comment by bruth** [comment]
This actually *was* intended for the "Data_Models" repo. It is correct [here](https://github.com/chop-dbhi/data-models/blob/master/pedsnet/v2.1/schema/drug_exposure.csv#L27).
