### ISSUE TITLE
Document and enforce identifier naming rules

### ISSUE THREAD

**Issue by murphyke** [chop-dbhi/data-models#95]
If the intent is to support multiple databases, including Oracle, then identifiers must be no longer than 30 bytes and must begin with a letter.  This is a huge pain for constraint names, but c'est la vie.

A few changes to the existing data models will be required. E.g., there are a few PEDSnet v2 constraint names that need shortening:

31:fpk_concept_ancestor_concept_1
31:fpk_concept_ancestor_concept_2
31:fpk_observation_period_concept
31:fpk_person_ethnicity_concept_s

Changing the names could be disruptive to existing systems.

**Comment by aaron0browne** [comment]
Yes, see the result of this at PEDSnet/Data_Models#197 (which also points out a couple more constraints and one **column**).

**Comment by aaron0browne** [comment]
These are actually *exactly* 30 characters and were not reported as problematic by Oracle users. Closing.
