### ISSUE TITLE
Changes proposed to PCORnet 3.0.0 DDL scripts 

### ISSUE THREAD

**Issue by writetoritu** [chop-dbhi/data-models#97]

**Comment by aaron0browne** [comment]
What changes are you proposing, @writetoritu?

**Comment by writetoritu** [comment]
We (with @ldavidson ) will be updating this issue later today. Thanks!

**Comment by ldavidson** [comment]
the updated ddl can be found here:  https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/develop/v2%20to%20v3/ETL%20Scripts/pcornetcdm_ddl.sql
